import { Company, Criteria } from '@/types'

export const MOCK_CRITERIA: Criteria[] = [
  { id: 'c1', name: '복지', weight: 35, order: 0 },
  { id: 'c2', name: '집과의 거리', weight: 20, order: 1 },
  { id: 'c3', name: '연봉', weight: 20, order: 2 },
  { id: 'c4', name: '회사 규모', weight: 20, order: 3 },
  { id: 'c5', name: '기술 스택', weight: 5, order: 4 },
]

export const MOCK_COMPANIES: Company[] = [
  {
    id: '1',
    name: '토스플레이스',
    targetStatus: 'O',
    jobPostingUrl: 'https://www.wanted.co.kr',
    recruitmentDeadline: '2026-03-05',
    applicationStatus: 'APPLIED',
    memo: '핀테크 특화 팀, 성장 가능성 높음',
    scores: [
      { criteriaId: 'c1', actualInfo: '식대, 성과금, 비포괄, 통신비 지원', score: 100 },
      { criteriaId: 'c2', actualInfo: '강남역 근처, 재택 가능', score: 90 },
      { criteriaId: 'c3', actualInfo: '6000만원 이상 예상', score: 100 },
      { criteriaId: 'c4', actualInfo: '큰 규모의 서비스', score: 100 },
      { criteriaId: 'c5', actualInfo: 'jvm계열, kafka, redis', score: 100 },
    ],
    createdAt: '2026-01-10T00:00:00.000Z',
    updatedAt: '2026-02-01T00:00:00.000Z',
  },
  {
    id: '2',
    name: '카카오페이 - 결제',
    targetStatus: 'O',
    jobPostingUrl: 'https://www.wanted.co.kr',
    recruitmentDeadline: undefined,
    applicationStatus: 'NOT_APPLIED',
    memo: '',
    scores: [
      { criteriaId: 'c1', actualInfo: '현금성복지 존재', score: 100 },
      { criteriaId: 'c2', actualInfo: '판교', score: 50 },
      { criteriaId: 'c3', actualInfo: '6000만원 이상 예상', score: 100 },
      { criteriaId: 'c4', actualInfo: '큰 규모의 서비스', score: 100 },
      { criteriaId: 'c5', actualInfo: 'jvm계열, kafka', score: 100 },
    ],
    createdAt: '2026-01-12T00:00:00.000Z',
    updatedAt: '2026-01-12T00:00:00.000Z',
  },
  {
    id: '3',
    name: '증권플러스비상장',
    targetStatus: 'O',
    jobPostingUrl: 'https://www.wanted.co.kr',
    recruitmentDeadline: '2026-03-12',
    applicationStatus: 'NOT_APPLIED',
    memo: '',
    scores: [
      { criteriaId: 'c1', actualInfo: '비포괄, 통신비 지원', score: 90 },
      { criteriaId: 'c2', actualInfo: '강남역 근처', score: 70 },
      { criteriaId: 'c3', actualInfo: '6000만원 이상 예상', score: 100 },
      { criteriaId: 'c4', actualInfo: '누적 가입자 160만', score: 100 },
      { criteriaId: 'c5', actualInfo: 'jvm계열, kafka, redis', score: 100 },
    ],
    createdAt: '2026-01-15T00:00:00.000Z',
    updatedAt: '2026-01-15T00:00:00.000Z',
  },
  {
    id: '4',
    name: '프리윌린',
    targetStatus: '△',
    jobPostingUrl: 'https://www.wanted.co.kr',
    recruitmentDeadline: undefined,
    applicationStatus: 'NOT_APPLIED',
    memo: '',
    scores: [
      { criteriaId: 'c1', actualInfo: '식대 제공, 비포괄', score: 90 },
      { criteriaId: 'c2', actualInfo: '서울대 입구역', score: 65 },
      { criteriaId: 'c3', actualInfo: '5000만원 중반', score: 20 },
      { criteriaId: 'c4', actualInfo: '누적 사용자 350만', score: 70 },
      { criteriaId: 'c5', actualInfo: 'jvm계열, redis', score: 100 },
    ],
    createdAt: '2026-01-18T00:00:00.000Z',
    updatedAt: '2026-01-18T00:00:00.000Z',
  },
  {
    id: '5',
    name: '마이리얼트립',
    targetStatus: '△',
    jobPostingUrl: 'https://www.wanted.co.kr',
    recruitmentDeadline: undefined,
    applicationStatus: 'FIRST_INTERVIEW',
    memo: '',
    scores: [
      { criteriaId: 'c1', actualInfo: '식대 제공, 개인변화 지원', score: 70 },
      { criteriaId: 'c2', actualInfo: '강남역 10분 거리', score: 65 },
      { criteriaId: 'c3', actualInfo: '5000만원 후반', score: 60 },
      { criteriaId: 'c4', actualInfo: '월간 수백만 건 결제', score: 78 },
      { criteriaId: 'c5', actualInfo: 'jvm계열, MSA', score: 100 },
    ],
    createdAt: '2026-01-20T00:00:00.000Z',
    updatedAt: '2026-02-10T00:00:00.000Z',
  },
  {
    id: '6',
    name: '미리디',
    targetStatus: '△',
    jobPostingUrl: 'https://www.wanted.co.kr',
    recruitmentDeadline: undefined,
    applicationStatus: 'REJECTED',
    memo: '',
    scores: [
      { criteriaId: 'c1', actualInfo: '식대 제공', score: 50 },
      { criteriaId: 'c2', actualInfo: '구로디지털단지', score: 70 },
      { criteriaId: 'c3', actualInfo: '5000만원 후반', score: 60 },
      { criteriaId: 'c4', actualInfo: '매출 780억, 흑자', score: 72 },
      { criteriaId: 'c5', actualInfo: '자바, webflux', score: 100 },
    ],
    createdAt: '2026-01-22T00:00:00.000Z',
    updatedAt: '2026-02-15T00:00:00.000Z',
  },
  {
    id: '7',
    name: '삼라이브',
    targetStatus: '△',
    jobPostingUrl: 'https://www.wanted.co.kr',
    recruitmentDeadline: undefined,
    applicationStatus: 'NOT_APPLIED',
    memo: '',
    scores: [
      { criteriaId: 'c1', actualInfo: '식대 제공', score: 50 },
      { criteriaId: 'c2', actualInfo: '선릉역 근처', score: 60 },
      { criteriaId: 'c3', actualInfo: '5000만원 후반', score: 60 },
      { criteriaId: 'c4', actualInfo: '누적 시청자 3억+', score: 80 },
      { criteriaId: 'c5', actualInfo: '자바, 스프링', score: 100 },
    ],
    createdAt: '2026-01-25T00:00:00.000Z',
    updatedAt: '2026-01-25T00:00:00.000Z',
  },
]
